
name: Linux Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Linux Build
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Installing LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Building the game
        run: |
          haxelib run lime build android
      # - name: Tar files
      #   run: tar -zcvf CodenameEngine.tar.gz -C export/release/linux/bin .
      - name: Uploading artifact (executable)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine (Executable Only)
          path: export/release/android/bin/CodenameEngine
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine
          path: export/release/android/bin/
